# Generated by Django 4.1.7 on 2023-03-08 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_do', models.DateTimeField()),
                ('action', models.CharField(max_length=254)),
                ('place_to_do', models.CharField(blank=True, max_length=254, null=True)),
                ('reward', models.CharField(blank=True, max_length=254, null=True)),
                ('is_related', models.BooleanField()),
                ('is_private', models.BooleanField(default=True)),
                ('periodicity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('time_for_execute', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
